FROM node:14

RUN mkdir -p /opt/app

WORKDIR /opt/app

COPY ./appfolder/package*.json ./

# RUN npm install --quiet
RUN npm install
RUN npm install nodemon --quiet
COPY ./appfolder/. .
EXPOSE 3005

# Inicia la aplicación al iniciar al contenedor
# CMD npx nodemon --legacy-watch index.js

# CMD [ "npx", "nodemon", "-L" "index.js" ]
CMD [ "npx", "nodemon", "index.js" ]