# version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: "mongodb://mongodb:27017/test"
      MY_CHAR: "Rick"
    ports:
      - "3000-3001:3000"
    volumes:
      - ./appfolder:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
